/*
Copyright 2021 BlackRock, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/argoproj/argo-events/pkg/apis/eventbus/v1alpha1/generated.proto

package v1alpha1

import (
	fmt "fmt"

	common "github.com/argoproj/argo-events/pkg/apis/common"

	io "io"

	proto "github.com/gogo/protobuf/proto"
	github_com_gogo_protobuf_sortkeys "github.com/gogo/protobuf/sortkeys"
	k8s_io_api_core_v1 "k8s.io/api/core/v1"
	v1 "k8s.io/api/core/v1"
	resource "k8s.io/apimachinery/pkg/api/resource"

	math "math"
	math_bits "math/bits"
	reflect "reflect"
	strings "strings"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

func (m *BusConfig) Reset()      { *m = BusConfig{} }
func (*BusConfig) ProtoMessage() {}
func (*BusConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_871e47633eb7aad4, []int{0}
}
func (m *BusConfig) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *BusConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *BusConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BusConfig.Merge(m, src)
}
func (m *BusConfig) XXX_Size() int {
	return m.Size()
}
func (m *BusConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_BusConfig.DiscardUnknown(m)
}

var xxx_messageInfo_BusConfig proto.InternalMessageInfo

func (m *ContainerTemplate) Reset()      { *m = ContainerTemplate{} }
func (*ContainerTemplate) ProtoMessage() {}
func (*ContainerTemplate) Descriptor() ([]byte, []int) {
	return fileDescriptor_871e47633eb7aad4, []int{1}
}
func (m *ContainerTemplate) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ContainerTemplate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *ContainerTemplate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContainerTemplate.Merge(m, src)
}
func (m *ContainerTemplate) XXX_Size() int {
	return m.Size()
}
func (m *ContainerTemplate) XXX_DiscardUnknown() {
	xxx_messageInfo_ContainerTemplate.DiscardUnknown(m)
}

var xxx_messageInfo_ContainerTemplate proto.InternalMessageInfo

func (m *EventBus) Reset()      { *m = EventBus{} }
func (*EventBus) ProtoMessage() {}
func (*EventBus) Descriptor() ([]byte, []int) {
	return fileDescriptor_871e47633eb7aad4, []int{2}
}
func (m *EventBus) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventBus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *EventBus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventBus.Merge(m, src)
}
func (m *EventBus) XXX_Size() int {
	return m.Size()
}
func (m *EventBus) XXX_DiscardUnknown() {
	xxx_messageInfo_EventBus.DiscardUnknown(m)
}

var xxx_messageInfo_EventBus proto.InternalMessageInfo

func (m *EventBusList) Reset()      { *m = EventBusList{} }
func (*EventBusList) ProtoMessage() {}
func (*EventBusList) Descriptor() ([]byte, []int) {
	return fileDescriptor_871e47633eb7aad4, []int{3}
}
func (m *EventBusList) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventBusList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *EventBusList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventBusList.Merge(m, src)
}
func (m *EventBusList) XXX_Size() int {
	return m.Size()
}
func (m *EventBusList) XXX_DiscardUnknown() {
	xxx_messageInfo_EventBusList.DiscardUnknown(m)
}

var xxx_messageInfo_EventBusList proto.InternalMessageInfo

func (m *EventBusSpec) Reset()      { *m = EventBusSpec{} }
func (*EventBusSpec) ProtoMessage() {}
func (*EventBusSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_871e47633eb7aad4, []int{4}
}
func (m *EventBusSpec) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventBusSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *EventBusSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventBusSpec.Merge(m, src)
}
func (m *EventBusSpec) XXX_Size() int {
	return m.Size()
}
func (m *EventBusSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_EventBusSpec.DiscardUnknown(m)
}

var xxx_messageInfo_EventBusSpec proto.InternalMessageInfo

func (m *EventBusStatus) Reset()      { *m = EventBusStatus{} }
func (*EventBusStatus) ProtoMessage() {}
func (*EventBusStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_871e47633eb7aad4, []int{5}
}
func (m *EventBusStatus) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventBusStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *EventBusStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventBusStatus.Merge(m, src)
}
func (m *EventBusStatus) XXX_Size() int {
	return m.Size()
}
func (m *EventBusStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_EventBusStatus.DiscardUnknown(m)
}

var xxx_messageInfo_EventBusStatus proto.InternalMessageInfo

func (m *NATSBus) Reset()      { *m = NATSBus{} }
func (*NATSBus) ProtoMessage() {}
func (*NATSBus) Descriptor() ([]byte, []int) {
	return fileDescriptor_871e47633eb7aad4, []int{6}
}
func (m *NATSBus) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *NATSBus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *NATSBus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NATSBus.Merge(m, src)
}
func (m *NATSBus) XXX_Size() int {
	return m.Size()
}
func (m *NATSBus) XXX_DiscardUnknown() {
	xxx_messageInfo_NATSBus.DiscardUnknown(m)
}

var xxx_messageInfo_NATSBus proto.InternalMessageInfo

func (m *NATSConfig) Reset()      { *m = NATSConfig{} }
func (*NATSConfig) ProtoMessage() {}
func (*NATSConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_871e47633eb7aad4, []int{7}
}
func (m *NATSConfig) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *NATSConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *NATSConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NATSConfig.Merge(m, src)
}
func (m *NATSConfig) XXX_Size() int {
	return m.Size()
}
func (m *NATSConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_NATSConfig.DiscardUnknown(m)
}

var xxx_messageInfo_NATSConfig proto.InternalMessageInfo

func (m *NativeStrategy) Reset()      { *m = NativeStrategy{} }
func (*NativeStrategy) ProtoMessage() {}
func (*NativeStrategy) Descriptor() ([]byte, []int) {
	return fileDescriptor_871e47633eb7aad4, []int{8}
}
func (m *NativeStrategy) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *NativeStrategy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *NativeStrategy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NativeStrategy.Merge(m, src)
}
func (m *NativeStrategy) XXX_Size() int {
	return m.Size()
}
func (m *NativeStrategy) XXX_DiscardUnknown() {
	xxx_messageInfo_NativeStrategy.DiscardUnknown(m)
}

var xxx_messageInfo_NativeStrategy proto.InternalMessageInfo

func (m *PersistenceStrategy) Reset()      { *m = PersistenceStrategy{} }
func (*PersistenceStrategy) ProtoMessage() {}
func (*PersistenceStrategy) Descriptor() ([]byte, []int) {
	return fileDescriptor_871e47633eb7aad4, []int{9}
}
func (m *PersistenceStrategy) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PersistenceStrategy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *PersistenceStrategy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PersistenceStrategy.Merge(m, src)
}
func (m *PersistenceStrategy) XXX_Size() int {
	return m.Size()
}
func (m *PersistenceStrategy) XXX_DiscardUnknown() {
	xxx_messageInfo_PersistenceStrategy.DiscardUnknown(m)
}

var xxx_messageInfo_PersistenceStrategy proto.InternalMessageInfo

func init() {
	proto.RegisterType((*BusConfig)(nil), "github.com.argoproj.argo_events.pkg.apis.eventbus.v1alpha1.BusConfig")
	proto.RegisterType((*ContainerTemplate)(nil), "github.com.argoproj.argo_events.pkg.apis.eventbus.v1alpha1.ContainerTemplate")
	proto.RegisterType((*EventBus)(nil), "github.com.argoproj.argo_events.pkg.apis.eventbus.v1alpha1.EventBus")
	proto.RegisterType((*EventBusList)(nil), "github.com.argoproj.argo_events.pkg.apis.eventbus.v1alpha1.EventBusList")
	proto.RegisterType((*EventBusSpec)(nil), "github.com.argoproj.argo_events.pkg.apis.eventbus.v1alpha1.EventBusSpec")
	proto.RegisterType((*EventBusStatus)(nil), "github.com.argoproj.argo_events.pkg.apis.eventbus.v1alpha1.EventBusStatus")
	proto.RegisterType((*NATSBus)(nil), "github.com.argoproj.argo_events.pkg.apis.eventbus.v1alpha1.NATSBus")
	proto.RegisterType((*NATSConfig)(nil), "github.com.argoproj.argo_events.pkg.apis.eventbus.v1alpha1.NATSConfig")
	proto.RegisterType((*NativeStrategy)(nil), "github.com.argoproj.argo_events.pkg.apis.eventbus.v1alpha1.NativeStrategy")
	proto.RegisterMapType((map[string]string)(nil), "github.com.argoproj.argo_events.pkg.apis.eventbus.v1alpha1.NativeStrategy.NodeSelectorEntry")
	proto.RegisterType((*PersistenceStrategy)(nil), "github.com.argoproj.argo_events.pkg.apis.eventbus.v1alpha1.PersistenceStrategy")
}

func init() {
	proto.RegisterFile("github.com/argoproj/argo-events/pkg/apis/eventbus/v1alpha1/generated.proto", fileDescriptor_871e47633eb7aad4)
}

var fileDescriptor_871e47633eb7aad4 = []byte{
	// 1528 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x57, 0xdd, 0x6e, 0x13, 0xc7,
	0x17, 0xcf, 0xe6, 0xd3, 0x1e, 0x9b, 0x24, 0x9e, 0x84, 0x3f, 0xfb, 0x8f, 0xc0, 0x8e, 0x5c, 0x51,
	0x45, 0x2a, 0xac, 0x0b, 0xaa, 0x5a, 0xca, 0x0d, 0xcd, 0x86, 0x50, 0x42, 0xe3, 0x90, 0x8e, 0x03,
	0x52, 0x5b, 0x54, 0x3a, 0x59, 0x4f, 0x9c, 0x4d, 0x76, 0x77, 0xcc, 0xce, 0xac, 0x15, 0xf7, 0xaa,
	0xea, 0x13, 0xa0, 0x5e, 0x54, 0x7d, 0x83, 0xbe, 0x41, 0x9f, 0x81, 0x8b, 0x5e, 0x70, 0x57, 0xae,
	0x2c, 0x30, 0xea, 0x4b, 0x70, 0x55, 0xcd, 0xec, 0xec, 0x87, 0xbd, 0x0e, 0x0d, 0x24, 0xbd, 0xf2,
	0xce, 0xf9, 0xf8, 0xfd, 0xce, 0x39, 0x73, 0xe6, 0xcc, 0x18, 0xdc, 0x6b, 0xd9, 0x7c, 0x3f, 0xd8,
	0x35, 0x2c, 0xea, 0xd6, 0xb0, 0xdf, 0xa2, 0x6d, 0x9f, 0x1e, 0xc8, 0x8f, 0xab, 0xa4, 0x43, 0x3c,
	0xce, 0x6a, 0xed, 0xc3, 0x56, 0x0d, 0xb7, 0x6d, 0x56, 0x93, 0xeb, 0xdd, 0x80, 0xd5, 0x3a, 0xd7,
	0xb0, 0xd3, 0xde, 0xc7, 0xd7, 0x6a, 0x2d, 0xe2, 0x11, 0x1f, 0x73, 0xd2, 0x34, 0xda, 0x3e, 0xe5,
	0x14, 0xde, 0x4c, 0xb0, 0x8c, 0x08, 0x4b, 0x7e, 0x3c, 0x0e, 0xb1, 0x8c, 0xf6, 0x61, 0xcb, 0x10,
	0x58, 0x46, 0x84, 0x65, 0x44, 0x58, 0x4b, 0xb7, 0x4e, 0x1c, 0x87, 0x45, 0x5d, 0x97, 0x7a, 0xc3,
	0xe4, 0x4b, 0x57, 0x53, 0x00, 0x2d, 0xda, 0xa2, 0x35, 0x29, 0xde, 0x0d, 0xf6, 0xe4, 0x4a, 0x2e,
	0xe4, 0x97, 0x32, 0xaf, 0x1e, 0xde, 0x60, 0x86, 0x4d, 0x05, 0x64, 0xcd, 0xa2, 0x3e, 0xa9, 0x75,
	0x32, 0xf9, 0x2c, 0x7d, 0x92, 0xd8, 0xb8, 0xd8, 0xda, 0xb7, 0x3d, 0xe2, 0x77, 0xa3, 0x38, 0x6a,
	0x3e, 0x61, 0x34, 0xf0, 0x2d, 0xf2, 0x4e, 0x5e, 0xac, 0xe6, 0x12, 0x8e, 0x47, 0x71, 0xd5, 0x8e,
	0xf3, 0xf2, 0x03, 0x8f, 0xdb, 0x6e, 0x96, 0xe6, 0xd3, 0x7f, 0x73, 0x60, 0xd6, 0x3e, 0x71, 0xf1,
	0xb0, 0x5f, 0xf5, 0x09, 0xc8, 0x9b, 0x01, 0x5b, 0xa3, 0xde, 0x9e, 0xdd, 0x82, 0x4d, 0x30, 0xe9,
	0x61, 0xce, 0x74, 0x6d, 0x59, 0x5b, 0x29, 0x5c, 0xbf, 0x63, 0xbc, 0xff, 0x06, 0x1a, 0x5b, 0xab,
	0x3b, 0x8d, 0x10, 0xd5, 0xcc, 0xf5, 0x7b, 0x95, 0x49, 0xb1, 0x46, 0x12, 0xbd, 0xfa, 0xc7, 0x38,
	0x28, 0xad, 0x51, 0x8f, 0x63, 0x11, 0xe4, 0x0e, 0x71, 0xdb, 0x0e, 0xe6, 0x04, 0x7e, 0x03, 0xf2,
	0x51, 0x0d, 0xa3, 0x00, 0x56, 0x8c, 0x30, 0x29, 0xc1, 0x61, 0x88, 0x5d, 0x31, 0x3a, 0xd7, 0x0c,
	0xa4, 0x8c, 0x10, 0x79, 0x12, 0xd8, 0x3e, 0x71, 0x45, 0x20, 0x66, 0xe9, 0x59, 0xaf, 0x32, 0xd6,
	0xef, 0x55, 0xf2, 0x91, 0x96, 0xa1, 0x04, 0x0d, 0xee, 0x82, 0x39, 0xdb, 0xc5, 0x2d, 0xb2, 0x1d,
	0x38, 0xce, 0x36, 0x75, 0x6c, 0xab, 0xab, 0x8f, 0x2f, 0x6b, 0x2b, 0x79, 0xf3, 0x86, 0x72, 0x9b,
	0xdb, 0x18, 0x54, 0xbf, 0xe9, 0x55, 0x2e, 0x65, 0x1b, 0xc2, 0x48, 0x0c, 0xd0, 0x30, 0xa0, 0xe0,
	0x60, 0xc4, 0x0a, 0x7c, 0x9b, 0x77, 0x45, 0x6e, 0xe4, 0x88, 0xeb, 0x13, 0x32, 0x89, 0x0f, 0x46,
	0x25, 0xd1, 0x18, 0x34, 0x35, 0x17, 0x44, 0x10, 0x43, 0x42, 0x34, 0x0c, 0x58, 0xfd, 0x73, 0x1c,
	0xe4, 0xd6, 0x45, 0xa5, 0xcd, 0x80, 0xc1, 0x1f, 0x40, 0x4e, 0x34, 0x4f, 0x13, 0x73, 0xac, 0xca,
	0xf5, 0x71, 0x8a, 0x29, 0xee, 0x81, 0x64, 0x8f, 0x84, 0xb5, 0xe0, 0xbe, 0xbf, 0x7b, 0x40, 0x2c,
	0x5e, 0x27, 0x1c, 0x9b, 0x50, 0xe5, 0x0f, 0x12, 0x19, 0x8a, 0x51, 0xe1, 0x01, 0x98, 0x64, 0x6d,
	0x62, 0xc9, 0x5a, 0x15, 0xae, 0xdf, 0x3d, 0x4d, 0x37, 0x44, 0x51, 0x37, 0xda, 0xc4, 0x32, 0x8b,
	0x8a, 0x75, 0x52, 0xac, 0x90, 0xe4, 0x80, 0x3e, 0x98, 0x66, 0x1c, 0xf3, 0x80, 0xa9, 0xaa, 0xdd,
	0x3b, 0x13, 0x36, 0x89, 0x68, 0xce, 0x2a, 0xbe, 0xe9, 0x70, 0x8d, 0x14, 0x53, 0xf5, 0x2f, 0x0d,
	0x14, 0x23, 0xd3, 0x4d, 0x9b, 0x71, 0xf8, 0x28, 0x53, 0x52, 0xe3, 0x64, 0x25, 0x15, 0xde, 0xb2,
	0xa0, 0xf3, 0x8a, 0x2a, 0x17, 0x49, 0x52, 0xe5, 0xb4, 0xc1, 0x94, 0xcd, 0x89, 0xcb, 0xf4, 0xf1,
	0xe5, 0x89, 0x95, 0xc2, 0xf5, 0xdb, 0x67, 0x91, 0xa1, 0x79, 0x4e, 0x11, 0x4e, 0x6d, 0x08, 0x68,
	0x14, 0x32, 0x54, 0x9f, 0x24, 0x89, 0x89, 0x1a, 0x43, 0x3c, 0x70, 0xae, 0xd7, 0x4e, 0x7b, 0xae,
	0x05, 0xf1, 0xf0, 0xa1, 0x7e, 0xa9, 0x81, 0xd9, 0xc1, 0xba, 0xc3, 0xc7, 0xf1, 0x9e, 0x86, 0xbc,
	0x9f, 0x9d, 0x9c, 0x37, 0x1c, 0xea, 0xc6, 0xdb, 0x37, 0x10, 0xba, 0x60, 0xda, 0x92, 0x23, 0x46,
	0xb5, 0xe8, 0xfa, 0x69, 0x12, 0x8b, 0xa7, 0x60, 0x42, 0x17, 0xae, 0x91, 0x22, 0xa9, 0xfe, 0xad,
	0x81, 0x19, 0x95, 0x3e, 0xf4, 0xc0, 0xb4, 0x87, 0xb9, 0xdd, 0x21, 0x2a, 0xb7, 0x53, 0xf5, 0xeb,
	0x96, 0x44, 0x6a, 0x70, 0x31, 0x97, 0x5b, 0x5d, 0x13, 0x08, 0xee, 0x50, 0x86, 0x14, 0x0b, 0x3c,
	0x00, 0xd3, 0xe4, 0x88, 0x72, 0x3b, 0x3a, 0x8d, 0x67, 0x35, 0x9b, 0x25, 0xd7, 0xba, 0x44, 0x46,
	0x8a, 0xa1, 0xfa, 0x5a, 0x03, 0x20, 0x31, 0x81, 0x97, 0xc0, 0x44, 0xe0, 0x3b, 0x32, 0xcf, 0xbc,
	0x59, 0x50, 0xb5, 0x99, 0x78, 0x80, 0x36, 0x91, 0x90, 0xc3, 0x8f, 0x40, 0xde, 0x72, 0x02, 0xc6,
	0x89, 0xbf, 0x71, 0x5b, 0x8d, 0xd5, 0x73, 0x62, 0x12, 0xaf, 0x45, 0x42, 0x94, 0xe8, 0xe1, 0x15,
	0x30, 0x89, 0x03, 0xbe, 0x2f, 0x0f, 0x79, 0xde, 0xd4, 0x45, 0x0f, 0xad, 0x06, 0x7c, 0xff, 0x4d,
	0xaf, 0x52, 0x14, 0xbf, 0x51, 0x09, 0x90, 0xb4, 0x82, 0xdf, 0x81, 0x22, 0xb6, 0x2c, 0xc2, 0x58,
	0x83, 0x58, 0x3e, 0xe1, 0xfa, 0xa4, 0x4c, 0xfd, 0xf2, 0x31, 0x03, 0xd5, 0x27, 0xfc, 0x2b, 0xd2,
	0x6d, 0x10, 0x87, 0x58, 0x9c, 0xfa, 0xe6, 0x7c, 0x5f, 0x80, 0xa6, 0xdc, 0xd1, 0x00, 0x58, 0xf5,
	0xe9, 0x1c, 0x98, 0x1d, 0x2c, 0x3c, 0xbc, 0x02, 0x72, 0x3e, 0x69, 0x3b, 0xb6, 0x85, 0xc3, 0x96,
	0x9d, 0x4a, 0xce, 0x33, 0x52, 0x72, 0x14, 0x5b, 0xc4, 0xb9, 0x8c, 0x9f, 0x28, 0x97, 0x9f, 0x35,
	0x50, 0x68, 0x13, 0x9f, 0xd9, 0x8c, 0x13, 0xcf, 0x22, 0x6a, 0xcc, 0xdd, 0x3f, 0xcd, 0x36, 0x6e,
	0x27, 0x70, 0x71, 0xef, 0xcc, 0xf5, 0x7b, 0x95, 0x42, 0x4a, 0x81, 0xd2, 0xa4, 0xf0, 0x17, 0x0d,
	0x94, 0xac, 0xe1, 0x9b, 0x57, 0x95, 0xb5, 0x7e, 0x9a, 0x50, 0x32, 0xd7, 0xb9, 0x79, 0xbe, 0xdf,
	0xab, 0x64, 0x6f, 0x79, 0x94, 0xa5, 0x87, 0xbf, 0x6b, 0x40, 0x77, 0x09, 0xf7, 0x6d, 0x8b, 0x65,
	0xec, 0xf5, 0xa9, 0xff, 0x22, 0xb6, 0x8b, 0xfd, 0x5e, 0x45, 0xaf, 0x1f, 0x43, 0x89, 0x8e, 0x0d,
	0x06, 0xfe, 0xaa, 0x81, 0xa2, 0x47, 0x9b, 0x24, 0xea, 0x31, 0x7d, 0x5a, 0x4e, 0xf2, 0x47, 0x67,
	0x77, 0xf6, 0x8d, 0xad, 0x14, 0xfc, 0xba, 0xc7, 0xfd, 0xae, 0xb9, 0xa8, 0x5a, 0xb0, 0x98, 0x56,
	0xa1, 0x81, 0x38, 0xe0, 0x03, 0x50, 0xe0, 0xd4, 0x11, 0xef, 0x3a, 0x9b, 0x7a, 0x4c, 0x9f, 0x91,
	0x61, 0x95, 0x47, 0x9d, 0x93, 0x9d, 0xd8, 0xcc, 0x5c, 0x50, 0xc0, 0x85, 0x44, 0xc6, 0x50, 0x1a,
	0x07, 0x5a, 0xa9, 0xfb, 0x30, 0x27, 0x37, 0xe2, 0xf3, 0x77, 0x1e, 0xe1, 0x75, 0x05, 0x60, 0x16,
	0xc5, 0x31, 0x8a, 0x56, 0xa9, 0x6b, 0x91, 0x64, 0x1f, 0x4e, 0x79, 0xc9, 0xf5, 0xe1, 0xa8, 0xf8,
	0xb7, 0x69, 0xf3, 0xbd, 0xde, 0x4e, 0xb0, 0x0a, 0xa6, 0x5d, 0x7c, 0xb4, 0xda, 0x22, 0x3a, 0x90,
	0xe7, 0x55, 0x0e, 0xbe, 0xba, 0x94, 0x20, 0xa5, 0x81, 0x1e, 0x98, 0x8f, 0x9f, 0x75, 0xe1, 0x94,
	0x60, 0x7a, 0x41, 0xd6, 0x72, 0xe4, 0x4b, 0x74, 0x93, 0x5a, 0xd8, 0x09, 0x5f, 0x4e, 0x88, 0xec,
	0x11, 0x5f, 0x1c, 0x31, 0x53, 0x57, 0x55, 0x9d, 0xdf, 0x18, 0x42, 0x42, 0x19, 0x6c, 0x78, 0x0f,
	0x40, 0x46, 0xfc, 0x8e, 0x6d, 0x91, 0x55, 0xcb, 0xa2, 0x81, 0xc7, 0xb7, 0xb0, 0x4b, 0xf4, 0xa2,
	0x8c, 0x6f, 0x49, 0xe1, 0xc0, 0x46, 0xc6, 0x02, 0x8d, 0xf0, 0x82, 0x5f, 0x82, 0x52, 0xdb, 0xb7,
	0xa9, 0x4c, 0xd9, 0xc1, 0x8c, 0x49, 0xa8, 0x73, 0x12, 0xea, 0xff, 0x0a, 0xaa, 0xb4, 0x3d, 0x6c,
	0x80, 0xb2, 0x3e, 0x70, 0x05, 0xe4, 0x22, 0xa1, 0x3e, 0x2b, 0x87, 0xa0, 0xdc, 0xb9, 0xc8, 0x17,
	0xc5, 0x5a, 0x78, 0x07, 0xe4, 0xf0, 0xde, 0x9e, 0xed, 0x09, 0xcb, 0x39, 0xb9, 0x65, 0x17, 0x47,
	0x95, 0x69, 0x55, 0xd9, 0x84, 0x38, 0xd1, 0x0a, 0xc5, 0xbe, 0xf0, 0x32, 0x98, 0x71, 0xf1, 0x51,
	0x9d, 0xb5, 0x98, 0x3e, 0xbf, 0xac, 0xad, 0x4c, 0x9a, 0x85, 0x7e, 0xaf, 0x32, 0x53, 0x0f, 0x45,
	0x28, 0xd2, 0x89, 0xc0, 0x5c, 0x7c, 0x64, 0x76, 0x39, 0x61, 0x7a, 0x49, 0x26, 0x16, 0xb6, 0x94,
	0x92, 0xa1, 0x58, 0xab, 0x00, 0x1b, 0xc1, 0x2e, 0xd3, 0xe1, 0x00, 0xa0, 0x10, 0xa1, 0x48, 0x07,
	0x0d, 0x00, 0x5c, 0x7c, 0xb4, 0x8d, 0xbb, 0x0e, 0xc5, 0x4d, 0x7d, 0x41, 0x42, 0xce, 0x8a, 0xd7,
	0x70, 0x3d, 0x96, 0xa2, 0x94, 0x05, 0xdc, 0x04, 0x8b, 0x3e, 0xde, 0xe3, 0x77, 0x09, 0xf6, 0xf9,
	0x2e, 0xc1, 0x7c, 0xc7, 0x76, 0x09, 0x0d, 0xb8, 0xbe, 0x18, 0x5f, 0x00, 0x8b, 0x68, 0x84, 0x1e,
	0x8d, 0xf4, 0x82, 0x1b, 0x60, 0x41, 0xc8, 0xd7, 0xc5, 0x11, 0xb6, 0xa9, 0x17, 0x81, 0x9d, 0x97,
	0x60, 0x17, 0xfa, 0xbd, 0xca, 0x02, 0xca, 0xaa, 0xd1, 0x28, 0x1f, 0xf8, 0x05, 0x98, 0x17, 0xe2,
	0x4d, 0x82, 0x19, 0x89, 0x70, 0xfe, 0x27, 0x71, 0x16, 0x45, 0x27, 0xa2, 0x21, 0x1d, 0xca, 0x58,
	0xc3, 0x35, 0x50, 0x12, 0xb2, 0x35, 0xea, 0xba, 0x76, 0x9c, 0xd7, 0x05, 0x09, 0x21, 0x07, 0x39,
	0x1a, 0x56, 0xa2, 0xac, 0xfd, 0xd2, 0x2d, 0x50, 0xca, 0x8c, 0x2f, 0x38, 0x0f, 0x26, 0x0e, 0x49,
	0x37, 0x7c, 0x3d, 0x20, 0xf1, 0x09, 0x17, 0xc1, 0x54, 0x07, 0x3b, 0x01, 0x09, 0x2f, 0x4e, 0x14,
	0x2e, 0x6e, 0x8e, 0xdf, 0xd0, 0xaa, 0xbf, 0x8d, 0x83, 0x85, 0x11, 0x97, 0x9a, 0xc8, 0x8f, 0x71,
	0xea, 0xe3, 0x16, 0x49, 0x5a, 0x5b, 0x4b, 0xf2, 0x6b, 0x0c, 0xe9, 0x50, 0xc6, 0x1a, 0x3e, 0x06,
	0x20, 0xbc, 0xfc, 0xeb, 0xb4, 0xa9, 0x88, 0xcd, 0x5b, 0x62, 0xab, 0x57, 0x63, 0xe9, 0x9b, 0x5e,
	0xe5, 0xea, 0xa8, 0xff, 0x7c, 0x51, 0x3c, 0xfc, 0x21, 0x75, 0x02, 0x97, 0x24, 0x0e, 0x28, 0x05,
	0x09, 0xbf, 0x07, 0xa0, 0x23, 0xf5, 0x0d, 0xfb, 0xc7, 0xe8, 0x72, 0x7f, 0xeb, 0x9f, 0x07, 0x23,
	0xfa, 0x7b, 0x6a, 0x7c, 0x1d, 0x60, 0x8f, 0x8b, 0xf3, 0x21, 0x7b, 0xef, 0x61, 0x8c, 0x82, 0x52,
	0x88, 0xa6, 0xf1, 0xec, 0x55, 0x79, 0xec, 0xf9, 0xab, 0xf2, 0xd8, 0x8b, 0x57, 0xe5, 0xb1, 0x9f,
	0xfa, 0x65, 0xed, 0x59, 0xbf, 0xac, 0x3d, 0xef, 0x97, 0xb5, 0x17, 0xfd, 0xb2, 0xf6, 0xb2, 0x5f,
	0xd6, 0x9e, 0xbe, 0x2e, 0x8f, 0x7d, 0x9b, 0x8b, 0xae, 0x95, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff,
	0x10, 0x2c, 0x4c, 0x24, 0xc8, 0x11, 0x00, 0x00,
}

func (m *BusConfig) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BusConfig) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *BusConfig) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.NATS != nil {
		{
			size, err := m.NATS.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintGenerated(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ContainerTemplate) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ContainerTemplate) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ContainerTemplate) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.SecurityContext != nil {
		{
			size, err := m.SecurityContext.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintGenerated(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	i -= len(m.ImagePullPolicy)
	copy(dAtA[i:], m.ImagePullPolicy)
	i = encodeVarintGenerated(dAtA, i, uint64(len(m.ImagePullPolicy)))
	i--
	dAtA[i] = 0x12
	{
		size, err := m.Resources.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenerated(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *EventBus) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventBus) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventBus) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Status.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenerated(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size, err := m.Spec.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenerated(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size, err := m.ObjectMeta.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenerated(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *EventBusList) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventBusList) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventBusList) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Items) > 0 {
		for iNdEx := len(m.Items) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Items[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenerated(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.ListMeta.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenerated(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *EventBusSpec) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventBusSpec) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventBusSpec) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.NATS != nil {
		{
			size, err := m.NATS.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintGenerated(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *EventBusStatus) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventBusStatus) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventBusStatus) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Config.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenerated(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size, err := m.Status.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenerated(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *NATSBus) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *NATSBus) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *NATSBus) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Exotic != nil {
		{
			size, err := m.Exotic.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintGenerated(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.Native != nil {
		{
			size, err := m.Native.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintGenerated(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *NATSConfig) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *NATSConfig) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *NATSConfig) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.AccessSecret != nil {
		{
			size, err := m.AccessSecret.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintGenerated(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	if m.Auth != nil {
		i -= len(*m.Auth)
		copy(dAtA[i:], *m.Auth)
		i = encodeVarintGenerated(dAtA, i, uint64(len(*m.Auth)))
		i--
		dAtA[i] = 0x1a
	}
	if m.ClusterID != nil {
		i -= len(*m.ClusterID)
		copy(dAtA[i:], *m.ClusterID)
		i = encodeVarintGenerated(dAtA, i, uint64(len(*m.ClusterID)))
		i--
		dAtA[i] = 0x12
	}
	i -= len(m.URL)
	copy(dAtA[i:], m.URL)
	i = encodeVarintGenerated(dAtA, i, uint64(len(m.URL)))
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *NativeStrategy) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *NativeStrategy) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *NativeStrategy) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.RaftCommitTimeout != nil {
		i -= len(*m.RaftCommitTimeout)
		copy(dAtA[i:], *m.RaftCommitTimeout)
		i = encodeVarintGenerated(dAtA, i, uint64(len(*m.RaftCommitTimeout)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xba
	}
	if m.RaftLeaseTimeout != nil {
		i -= len(*m.RaftLeaseTimeout)
		copy(dAtA[i:], *m.RaftLeaseTimeout)
		i = encodeVarintGenerated(dAtA, i, uint64(len(*m.RaftLeaseTimeout)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xb2
	}
	if m.RaftElectionTimeout != nil {
		i -= len(*m.RaftElectionTimeout)
		copy(dAtA[i:], *m.RaftElectionTimeout)
		i = encodeVarintGenerated(dAtA, i, uint64(len(*m.RaftElectionTimeout)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xaa
	}
	if m.RaftHeartbeatTimeout != nil {
		i -= len(*m.RaftHeartbeatTimeout)
		copy(dAtA[i:], *m.RaftHeartbeatTimeout)
		i = encodeVarintGenerated(dAtA, i, uint64(len(*m.RaftHeartbeatTimeout)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xa2
	}
	if m.MaxPayload != nil {
		i -= len(*m.MaxPayload)
		copy(dAtA[i:], *m.MaxPayload)
		i = encodeVarintGenerated(dAtA, i, uint64(len(*m.MaxPayload)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x9a
	}
	if m.MaxSubs != nil {
		i = encodeVarintGenerated(dAtA, i, uint64(*m.MaxSubs))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x90
	}
	if m.MaxBytes != nil {
		i -= len(*m.MaxBytes)
		copy(dAtA[i:], *m.MaxBytes)
		i = encodeVarintGenerated(dAtA, i, uint64(len(*m.MaxBytes)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x8a
	}
	if m.MaxMsgs != nil {
		i = encodeVarintGenerated(dAtA, i, uint64(*m.MaxMsgs))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x80
	}
	if m.Affinity != nil {
		{
			size, err := m.Affinity.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintGenerated(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x7a
	}
	if m.Priority != nil {
		i = encodeVarintGenerated(dAtA, i, uint64(*m.Priority))
		i--
		dAtA[i] = 0x70
	}
	i -= len(m.PriorityClassName)
	copy(dAtA[i:], m.PriorityClassName)
	i = encodeVarintGenerated(dAtA, i, uint64(len(m.PriorityClassName)))
	i--
	dAtA[i] = 0x6a
	i -= len(m.ServiceAccountName)
	copy(dAtA[i:], m.ServiceAccountName)
	i = encodeVarintGenerated(dAtA, i, uint64(len(m.ServiceAccountName)))
	i--
	dAtA[i] = 0x62
	if len(m.ImagePullSecrets) > 0 {
		for iNdEx := len(m.ImagePullSecrets) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ImagePullSecrets[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenerated(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x5a
		}
	}
	if m.MaxAge != nil {
		i -= len(*m.MaxAge)
		copy(dAtA[i:], *m.MaxAge)
		i = encodeVarintGenerated(dAtA, i, uint64(len(*m.MaxAge)))
		i--
		dAtA[i] = 0x52
	}
	if m.SecurityContext != nil {
		{
			size, err := m.SecurityContext.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintGenerated(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x4a
	}
	if m.Metadata != nil {
		{
			size, err := m.Metadata.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintGenerated(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x42
	}
	if len(m.Tolerations) > 0 {
		for iNdEx := len(m.Tolerations) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Tolerations[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenerated(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x3a
		}
	}
	if len(m.NodeSelector) > 0 {
		keysForNodeSelector := make([]string, 0, len(m.NodeSelector))
		for k := range m.NodeSelector {
			keysForNodeSelector = append(keysForNodeSelector, string(k))
		}
		github_com_gogo_protobuf_sortkeys.Strings(keysForNodeSelector)
		for iNdEx := len(keysForNodeSelector) - 1; iNdEx >= 0; iNdEx-- {
			v := m.NodeSelector[string(keysForNodeSelector[iNdEx])]
			baseI := i
			i -= len(v)
			copy(dAtA[i:], v)
			i = encodeVarintGenerated(dAtA, i, uint64(len(v)))
			i--
			dAtA[i] = 0x12
			i -= len(keysForNodeSelector[iNdEx])
			copy(dAtA[i:], keysForNodeSelector[iNdEx])
			i = encodeVarintGenerated(dAtA, i, uint64(len(keysForNodeSelector[iNdEx])))
			i--
			dAtA[i] = 0xa
			i = encodeVarintGenerated(dAtA, i, uint64(baseI-i))
			i--
			dAtA[i] = 0x32
		}
	}
	if m.MetricsContainerTemplate != nil {
		{
			size, err := m.MetricsContainerTemplate.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintGenerated(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x2a
	}
	if m.ContainerTemplate != nil {
		{
			size, err := m.ContainerTemplate.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintGenerated(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	if m.Persistence != nil {
		{
			size, err := m.Persistence.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintGenerated(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.Auth != nil {
		i -= len(*m.Auth)
		copy(dAtA[i:], *m.Auth)
		i = encodeVarintGenerated(dAtA, i, uint64(len(*m.Auth)))
		i--
		dAtA[i] = 0x12
	}
	i = encodeVarintGenerated(dAtA, i, uint64(m.Replicas))
	i--
	dAtA[i] = 0x8
	return len(dAtA) - i, nil
}

func (m *PersistenceStrategy) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PersistenceStrategy) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PersistenceStrategy) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.VolumeSize != nil {
		{
			size, err := m.VolumeSize.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintGenerated(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.AccessMode != nil {
		i -= len(*m.AccessMode)
		copy(dAtA[i:], *m.AccessMode)
		i = encodeVarintGenerated(dAtA, i, uint64(len(*m.AccessMode)))
		i--
		dAtA[i] = 0x12
	}
	if m.StorageClassName != nil {
		i -= len(*m.StorageClassName)
		copy(dAtA[i:], *m.StorageClassName)
		i = encodeVarintGenerated(dAtA, i, uint64(len(*m.StorageClassName)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintGenerated(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenerated(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *BusConfig) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.NATS != nil {
		l = m.NATS.Size()
		n += 1 + l + sovGenerated(uint64(l))
	}
	return n
}

func (m *ContainerTemplate) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Resources.Size()
	n += 1 + l + sovGenerated(uint64(l))
	l = len(m.ImagePullPolicy)
	n += 1 + l + sovGenerated(uint64(l))
	if m.SecurityContext != nil {
		l = m.SecurityContext.Size()
		n += 1 + l + sovGenerated(uint64(l))
	}
	return n
}

func (m *EventBus) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.ObjectMeta.Size()
	n += 1 + l + sovGenerated(uint64(l))
	l = m.Spec.Size()
	n += 1 + l + sovGenerated(uint64(l))
	l = m.Status.Size()
	n += 1 + l + sovGenerated(uint64(l))
	return n
}

func (m *EventBusList) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.ListMeta.Size()
	n += 1 + l + sovGenerated(uint64(l))
	if len(m.Items) > 0 {
		for _, e := range m.Items {
			l = e.Size()
			n += 1 + l + sovGenerated(uint64(l))
		}
	}
	return n
}

func (m *EventBusSpec) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.NATS != nil {
		l = m.NATS.Size()
		n += 1 + l + sovGenerated(uint64(l))
	}
	return n
}

func (m *EventBusStatus) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Status.Size()
	n += 1 + l + sovGenerated(uint64(l))
	l = m.Config.Size()
	n += 1 + l + sovGenerated(uint64(l))
	return n
}

func (m *NATSBus) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Native != nil {
		l = m.Native.Size()
		n += 1 + l + sovGenerated(uint64(l))
	}
	if m.Exotic != nil {
		l = m.Exotic.Size()
		n += 1 + l + sovGenerated(uint64(l))
	}
	return n
}

func (m *NATSConfig) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.URL)
	n += 1 + l + sovGenerated(uint64(l))
	if m.ClusterID != nil {
		l = len(*m.ClusterID)
		n += 1 + l + sovGenerated(uint64(l))
	}
	if m.Auth != nil {
		l = len(*m.Auth)
		n += 1 + l + sovGenerated(uint64(l))
	}
	if m.AccessSecret != nil {
		l = m.AccessSecret.Size()
		n += 1 + l + sovGenerated(uint64(l))
	}
	return n
}

func (m *NativeStrategy) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += 1 + sovGenerated(uint64(m.Replicas))
	if m.Auth != nil {
		l = len(*m.Auth)
		n += 1 + l + sovGenerated(uint64(l))
	}
	if m.Persistence != nil {
		l = m.Persistence.Size()
		n += 1 + l + sovGenerated(uint64(l))
	}
	if m.ContainerTemplate != nil {
		l = m.ContainerTemplate.Size()
		n += 1 + l + sovGenerated(uint64(l))
	}
	if m.MetricsContainerTemplate != nil {
		l = m.MetricsContainerTemplate.Size()
		n += 1 + l + sovGenerated(uint64(l))
	}
	if len(m.NodeSelector) > 0 {
		for k, v := range m.NodeSelector {
			_ = k
			_ = v
			mapEntrySize := 1 + len(k) + sovGenerated(uint64(len(k))) + 1 + len(v) + sovGenerated(uint64(len(v)))
			n += mapEntrySize + 1 + sovGenerated(uint64(mapEntrySize))
		}
	}
	if len(m.Tolerations) > 0 {
		for _, e := range m.Tolerations {
			l = e.Size()
			n += 1 + l + sovGenerated(uint64(l))
		}
	}
	if m.Metadata != nil {
		l = m.Metadata.Size()
		n += 1 + l + sovGenerated(uint64(l))
	}
	if m.SecurityContext != nil {
		l = m.SecurityContext.Size()
		n += 1 + l + sovGenerated(uint64(l))
	}
	if m.MaxAge != nil {
		l = len(*m.MaxAge)
		n += 1 + l + sovGenerated(uint64(l))
	}
	if len(m.ImagePullSecrets) > 0 {
		for _, e := range m.ImagePullSecrets {
			l = e.Size()
			n += 1 + l + sovGenerated(uint64(l))
		}
	}
	l = len(m.ServiceAccountName)
	n += 1 + l + sovGenerated(uint64(l))
	l = len(m.PriorityClassName)
	n += 1 + l + sovGenerated(uint64(l))
	if m.Priority != nil {
		n += 1 + sovGenerated(uint64(*m.Priority))
	}
	if m.Affinity != nil {
		l = m.Affinity.Size()
		n += 1 + l + sovGenerated(uint64(l))
	}
	if m.MaxMsgs != nil {
		n += 2 + sovGenerated(uint64(*m.MaxMsgs))
	}
	if m.MaxBytes != nil {
		l = len(*m.MaxBytes)
		n += 2 + l + sovGenerated(uint64(l))
	}
	if m.MaxSubs != nil {
		n += 2 + sovGenerated(uint64(*m.MaxSubs))
	}
	if m.MaxPayload != nil {
		l = len(*m.MaxPayload)
		n += 2 + l + sovGenerated(uint64(l))
	}
	if m.RaftHeartbeatTimeout != nil {
		l = len(*m.RaftHeartbeatTimeout)
		n += 2 + l + sovGenerated(uint64(l))
	}
	if m.RaftElectionTimeout != nil {
		l = len(*m.RaftElectionTimeout)
		n += 2 + l + sovGenerated(uint64(l))
	}
	if m.RaftLeaseTimeout != nil {
		l = len(*m.RaftLeaseTimeout)
		n += 2 + l + sovGenerated(uint64(l))
	}
	if m.RaftCommitTimeout != nil {
		l = len(*m.RaftCommitTimeout)
		n += 2 + l + sovGenerated(uint64(l))
	}
	return n
}

func (m *PersistenceStrategy) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.StorageClassName != nil {
		l = len(*m.StorageClassName)
		n += 1 + l + sovGenerated(uint64(l))
	}
	if m.AccessMode != nil {
		l = len(*m.AccessMode)
		n += 1 + l + sovGenerated(uint64(l))
	}
	if m.VolumeSize != nil {
		l = m.VolumeSize.Size()
		n += 1 + l + sovGenerated(uint64(l))
	}
	return n
}

func sovGenerated(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenerated(x uint64) (n int) {
	return sovGenerated(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *BusConfig) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&BusConfig{`,
		`NATS:` + strings.Replace(this.NATS.String(), "NATSConfig", "NATSConfig", 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *ContainerTemplate) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&ContainerTemplate{`,
		`Resources:` + strings.Replace(strings.Replace(fmt.Sprintf("%v", this.Resources), "ResourceRequirements", "v1.ResourceRequirements", 1), `&`, ``, 1) + `,`,
		`ImagePullPolicy:` + fmt.Sprintf("%v", this.ImagePullPolicy) + `,`,
		`SecurityContext:` + strings.Replace(fmt.Sprintf("%v", this.SecurityContext), "SecurityContext", "v1.SecurityContext", 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *EventBus) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&EventBus{`,
		`ObjectMeta:` + strings.Replace(strings.Replace(fmt.Sprintf("%v", this.ObjectMeta), "ObjectMeta", "v11.ObjectMeta", 1), `&`, ``, 1) + `,`,
		`Spec:` + strings.Replace(strings.Replace(this.Spec.String(), "EventBusSpec", "EventBusSpec", 1), `&`, ``, 1) + `,`,
		`Status:` + strings.Replace(strings.Replace(this.Status.String(), "EventBusStatus", "EventBusStatus", 1), `&`, ``, 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *EventBusList) String() string {
	if this == nil {
		return "nil"
	}
	repeatedStringForItems := "[]EventBus{"
	for _, f := range this.Items {
		repeatedStringForItems += strings.Replace(strings.Replace(f.String(), "EventBus", "EventBus", 1), `&`, ``, 1) + ","
	}
	repeatedStringForItems += "}"
	s := strings.Join([]string{`&EventBusList{`,
		`ListMeta:` + strings.Replace(strings.Replace(fmt.Sprintf("%v", this.ListMeta), "ListMeta", "v11.ListMeta", 1), `&`, ``, 1) + `,`,
		`Items:` + repeatedStringForItems + `,`,
		`}`,
	}, "")
	return s
}
func (this *EventBusSpec) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&EventBusSpec{`,
		`NATS:` + strings.Replace(this.NATS.String(), "NATSBus", "NATSBus", 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *EventBusStatus) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&EventBusStatus{`,
		`Status:` + strings.Replace(strings.Replace(fmt.Sprintf("%v", this.Status), "Status", "common.Status", 1), `&`, ``, 1) + `,`,
		`Config:` + strings.Replace(strings.Replace(this.Config.String(), "BusConfig", "BusConfig", 1), `&`, ``, 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *NATSBus) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&NATSBus{`,
		`Native:` + strings.Replace(this.Native.String(), "NativeStrategy", "NativeStrategy", 1) + `,`,
		`Exotic:` + strings.Replace(this.Exotic.String(), "NATSConfig", "NATSConfig", 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *NATSConfig) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&NATSConfig{`,
		`URL:` + fmt.Sprintf("%v", this.URL) + `,`,
		`ClusterID:` + valueToStringGenerated(this.ClusterID) + `,`,
		`Auth:` + valueToStringGenerated(this.Auth) + `,`,
		`AccessSecret:` + strings.Replace(fmt.Sprintf("%v", this.AccessSecret), "SecretKeySelector", "v1.SecretKeySelector", 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *NativeStrategy) String() string {
	if this == nil {
		return "nil"
	}
	repeatedStringForTolerations := "[]Toleration{"
	for _, f := range this.Tolerations {
		repeatedStringForTolerations += fmt.Sprintf("%v", f) + ","
	}
	repeatedStringForTolerations += "}"
	repeatedStringForImagePullSecrets := "[]LocalObjectReference{"
	for _, f := range this.ImagePullSecrets {
		repeatedStringForImagePullSecrets += fmt.Sprintf("%v", f) + ","
	}
	repeatedStringForImagePullSecrets += "}"
	keysForNodeSelector := make([]string, 0, len(this.NodeSelector))
	for k := range this.NodeSelector {
		keysForNodeSelector = append(keysForNodeSelector, k)
	}
	github_com_gogo_protobuf_sortkeys.Strings(keysForNodeSelector)
	mapStringForNodeSelector := "map[string]string{"
	for _, k := range keysForNodeSelector {
		mapStringForNodeSelector += fmt.Sprintf("%v: %v,", k, this.NodeSelector[k])
	}
	mapStringForNodeSelector += "}"
	s := strings.Join([]string{`&NativeStrategy{`,
		`Replicas:` + fmt.Sprintf("%v", this.Replicas) + `,`,
		`Auth:` + valueToStringGenerated(this.Auth) + `,`,
		`Persistence:` + strings.Replace(this.Persistence.String(), "PersistenceStrategy", "PersistenceStrategy", 1) + `,`,
		`ContainerTemplate:` + strings.Replace(this.ContainerTemplate.String(), "ContainerTemplate", "ContainerTemplate", 1) + `,`,
		`MetricsContainerTemplate:` + strings.Replace(this.MetricsContainerTemplate.String(), "ContainerTemplate", "ContainerTemplate", 1) + `,`,
		`NodeSelector:` + mapStringForNodeSelector + `,`,
		`Tolerations:` + repeatedStringForTolerations + `,`,
		`Metadata:` + strings.Replace(fmt.Sprintf("%v", this.Metadata), "Metadata", "common.Metadata", 1) + `,`,
		`SecurityContext:` + strings.Replace(fmt.Sprintf("%v", this.SecurityContext), "PodSecurityContext", "v1.PodSecurityContext", 1) + `,`,
		`MaxAge:` + valueToStringGenerated(this.MaxAge) + `,`,
		`ImagePullSecrets:` + repeatedStringForImagePullSecrets + `,`,
		`ServiceAccountName:` + fmt.Sprintf("%v", this.ServiceAccountName) + `,`,
		`PriorityClassName:` + fmt.Sprintf("%v", this.PriorityClassName) + `,`,
		`Priority:` + valueToStringGenerated(this.Priority) + `,`,
		`Affinity:` + strings.Replace(fmt.Sprintf("%v", this.Affinity), "Affinity", "v1.Affinity", 1) + `,`,
		`MaxMsgs:` + valueToStringGenerated(this.MaxMsgs) + `,`,
		`MaxBytes:` + valueToStringGenerated(this.MaxBytes) + `,`,
		`MaxSubs:` + valueToStringGenerated(this.MaxSubs) + `,`,
		`MaxPayload:` + valueToStringGenerated(this.MaxPayload) + `,`,
		`RaftHeartbeatTimeout:` + valueToStringGenerated(this.RaftHeartbeatTimeout) + `,`,
		`RaftElectionTimeout:` + valueToStringGenerated(this.RaftElectionTimeout) + `,`,
		`RaftLeaseTimeout:` + valueToStringGenerated(this.RaftLeaseTimeout) + `,`,
		`RaftCommitTimeout:` + valueToStringGenerated(this.RaftCommitTimeout) + `,`,
		`}`,
	}, "")
	return s
}
func (this *PersistenceStrategy) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&PersistenceStrategy{`,
		`StorageClassName:` + valueToStringGenerated(this.StorageClassName) + `,`,
		`AccessMode:` + valueToStringGenerated(this.AccessMode) + `,`,
		`VolumeSize:` + strings.Replace(fmt.Sprintf("%v", this.VolumeSize), "Quantity", "resource.Quantity", 1) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringGenerated(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *BusConfig) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BusConfig: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BusConfig: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NATS", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.NATS == nil {
				m.NATS = &NATSConfig{}
			}
			if err := m.NATS.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ContainerTemplate) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ContainerTemplate: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ContainerTemplate: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Resources", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Resources.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ImagePullPolicy", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ImagePullPolicy = k8s_io_api_core_v1.PullPolicy(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SecurityContext", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.SecurityContext == nil {
				m.SecurityContext = &v1.SecurityContext{}
			}
			if err := m.SecurityContext.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventBus) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventBus: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventBus: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ObjectMeta", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ObjectMeta.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Spec", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Spec.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Status.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventBusList) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventBusList: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventBusList: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ListMeta", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ListMeta.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Items", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Items = append(m.Items, EventBus{})
			if err := m.Items[len(m.Items)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventBusSpec) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventBusSpec: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventBusSpec: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NATS", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.NATS == nil {
				m.NATS = &NATSBus{}
			}
			if err := m.NATS.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventBusStatus) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventBusStatus: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventBusStatus: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Status.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Config", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Config.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *NATSBus) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: NATSBus: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: NATSBus: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Native", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Native == nil {
				m.Native = &NativeStrategy{}
			}
			if err := m.Native.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Exotic", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Exotic == nil {
				m.Exotic = &NATSConfig{}
			}
			if err := m.Exotic.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *NATSConfig) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: NATSConfig: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: NATSConfig: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field URL", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.URL = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClusterID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.ClusterID = &s
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Auth", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := AuthStrategy(dAtA[iNdEx:postIndex])
			m.Auth = &s
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AccessSecret", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.AccessSecret == nil {
				m.AccessSecret = &v1.SecretKeySelector{}
			}
			if err := m.AccessSecret.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *NativeStrategy) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: NativeStrategy: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: NativeStrategy: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Replicas", wireType)
			}
			m.Replicas = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Replicas |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Auth", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := AuthStrategy(dAtA[iNdEx:postIndex])
			m.Auth = &s
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Persistence", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Persistence == nil {
				m.Persistence = &PersistenceStrategy{}
			}
			if err := m.Persistence.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContainerTemplate", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ContainerTemplate == nil {
				m.ContainerTemplate = &ContainerTemplate{}
			}
			if err := m.ContainerTemplate.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MetricsContainerTemplate", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.MetricsContainerTemplate == nil {
				m.MetricsContainerTemplate = &ContainerTemplate{}
			}
			if err := m.MetricsContainerTemplate.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NodeSelector", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.NodeSelector == nil {
				m.NodeSelector = make(map[string]string)
			}
			var mapkey string
			var mapvalue string
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowGenerated
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					var stringLenmapkey uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowGenerated
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapkey |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapkey := int(stringLenmapkey)
					if intStringLenmapkey < 0 {
						return ErrInvalidLengthGenerated
					}
					postStringIndexmapkey := iNdEx + intStringLenmapkey
					if postStringIndexmapkey < 0 {
						return ErrInvalidLengthGenerated
					}
					if postStringIndexmapkey > l {
						return io.ErrUnexpectedEOF
					}
					mapkey = string(dAtA[iNdEx:postStringIndexmapkey])
					iNdEx = postStringIndexmapkey
				} else if fieldNum == 2 {
					var stringLenmapvalue uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowGenerated
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapvalue |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapvalue := int(stringLenmapvalue)
					if intStringLenmapvalue < 0 {
						return ErrInvalidLengthGenerated
					}
					postStringIndexmapvalue := iNdEx + intStringLenmapvalue
					if postStringIndexmapvalue < 0 {
						return ErrInvalidLengthGenerated
					}
					if postStringIndexmapvalue > l {
						return io.ErrUnexpectedEOF
					}
					mapvalue = string(dAtA[iNdEx:postStringIndexmapvalue])
					iNdEx = postStringIndexmapvalue
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipGenerated(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if (skippy < 0) || (iNdEx+skippy) < 0 {
						return ErrInvalidLengthGenerated
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.NodeSelector[mapkey] = mapvalue
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tolerations", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Tolerations = append(m.Tolerations, v1.Toleration{})
			if err := m.Tolerations[len(m.Tolerations)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Metadata", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Metadata == nil {
				m.Metadata = &common.Metadata{}
			}
			if err := m.Metadata.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SecurityContext", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.SecurityContext == nil {
				m.SecurityContext = &v1.PodSecurityContext{}
			}
			if err := m.SecurityContext.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxAge", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.MaxAge = &s
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ImagePullSecrets", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ImagePullSecrets = append(m.ImagePullSecrets, v1.LocalObjectReference{})
			if err := m.ImagePullSecrets[len(m.ImagePullSecrets)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ServiceAccountName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ServiceAccountName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 13:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PriorityClassName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PriorityClassName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 14:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Priority", wireType)
			}
			var v int32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Priority = &v
		case 15:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Affinity", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Affinity == nil {
				m.Affinity = &v1.Affinity{}
			}
			if err := m.Affinity.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 16:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxMsgs", wireType)
			}
			var v uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.MaxMsgs = &v
		case 17:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxBytes", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.MaxBytes = &s
			iNdEx = postIndex
		case 18:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxSubs", wireType)
			}
			var v uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.MaxSubs = &v
		case 19:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxPayload", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.MaxPayload = &s
			iNdEx = postIndex
		case 20:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RaftHeartbeatTimeout", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.RaftHeartbeatTimeout = &s
			iNdEx = postIndex
		case 21:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RaftElectionTimeout", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.RaftElectionTimeout = &s
			iNdEx = postIndex
		case 22:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RaftLeaseTimeout", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.RaftLeaseTimeout = &s
			iNdEx = postIndex
		case 23:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RaftCommitTimeout", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.RaftCommitTimeout = &s
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PersistenceStrategy) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PersistenceStrategy: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PersistenceStrategy: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StorageClassName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.StorageClassName = &s
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AccessMode", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := k8s_io_api_core_v1.PersistentVolumeAccessMode(dAtA[iNdEx:postIndex])
			m.AccessMode = &s
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VolumeSize", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.VolumeSize == nil {
				m.VolumeSize = &resource.Quantity{}
			}
			if err := m.VolumeSize.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenerated(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenerated
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenerated
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenerated
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenerated        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenerated          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenerated = fmt.Errorf("proto: unexpected end of group")
)
