/*
Copyright 2018 BlackRock, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

	http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package slack

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io/ioutil"
	"net/http"
	"strings"

	"github.com/argoproj/argo-events/common"
	"github.com/argoproj/argo-events/gateways"
	gwcommon "github.com/argoproj/argo-events/gateways/common"
	"github.com/argoproj/argo-events/store"
	"github.com/nlopes/slack"
	"github.com/nlopes/slack/slackevents"
)

var (
	helper = gwcommon.NewWebhookHelper()
)

func init() {
	go gwcommon.InitRouteChannels(helper)
}

func (rc *RouteConfig) GetRoute() *gwcommon.Route {
	return rc.route
}

// RouteHandler handles new route
func (rc *RouteConfig) RouteHandler(writer http.ResponseWriter, request *http.Request) {
	r := rc.route

	log := r.Logger.WithFields(
		map[string]interface{}{
			common.LabelEventSource: r.EventSource.Name,
			common.LabelEndpoint:    r.Webhook.Endpoint,
			common.LabelPort:        r.Webhook.Port,
			common.LabelHTTPMethod:  r.Webhook.Method,
		})

	log.Info("request received")

	if !helper.ActiveEndpoints[r.Webhook.Endpoint].Active {
		log.Warn("endpoint is not active")
		common.SendErrorResponse(writer, "")
		return
	}

	//var buf bytes.Buffer
	//bufsize, err := buf.ReadFrom(request.Body)
	body, err := ioutil.ReadAll(request.Body)

	if err != nil {
		log.WithError(err).Error("failed to parse request body")
		common.SendInternalErrorResponse(writer, "")
		return
	}

	// if request.Header.Get("Content-Length") != string(bufsize) {
	// 	log.Warn("Content length mismatch")
	// 	log.Warn("Content-Length: " + request.Header.Get("Content-Length"))
	// 	log.Warn("Buffer Length: " + fmt.Sprintf("%d", bufsize))
	// 	log.Debug("Buffer: " + buf.String())
	// }

	log.Debug("request: ", request)
	//body := buf.String()
	log.Debug("body: " + string(body))

	// If a signing secret is provided, validate the request against the
	// X-Slack-Signature header value.
	// The signature is a hash generated as per Slack documentation at:
	// https://api.slack.com/docs/verifying-requests-from-slack
	signingSecret := rc.signingSecret
	if len(signingSecret) > 0 {
		log.Debug(">>>" + signingSecret + "<<<")
		sv, err := slack.NewSecretsVerifier(request.Header, signingSecret)
		if err != nil {
			log.WithError(err).Error("cannot create secrets verifier")
			common.SendInternalErrorResponse(writer, "")
			return
		}

		_, err = sv.Write([]byte(strings.TrimSuffix(string(body), "\n")))
		if err != nil {
			log.WithError(err).Error("error writing body: cannot verify signature")
			common.SendInternalErrorResponse(writer, "")
			return
		}
		// if int64(bw) != bufsize {
		// 	log.WithError(err).Error("size mismatch: cannot verify signature")
		// 	common.SendInternalErrorResponse(writer, "")
		// 	return
		// }

		err = sv.Ensure()
		if err != nil {
			log.Warn("body len: " + fmt.Sprintf("%d", len(body)))
			log.WithError(err).Error("signature validation failed")
			common.SendInternalErrorResponse(writer, "")
			return
		}

		// rts := request.Header.Get("X-Slack-Request-Timestamp")
		// sig := strings.TrimRight(request.Header.Get("X-Slack-Signature"), "\n")
		// h := hmac.New(sha256.New, []byte(signingSecret))
		// b := strings.Join([]string{"v0", rts, body}, ":")
		// h.Write([]byte(b))
		// hash := hex.EncodeToString(h.Sum(nil))
		// genSig := strings.TrimRight(strings.Join([]string{"v0=", hash}, ""), "\n")
		// log.Debug("Header Signature: ", sig)
		// log.Debug("Generated Signature: ", genSig)
		// if strings.Compare(genSig, sig) != 0 {
		// 	log.Error("signature validation failed")
		// 	common.SendInternalErrorResponse(writer, "")
		// 	return
		// }
	}

	// Restore the io.ReadCloser to its original state for the below step
	//request.Body = ioutil.NopCloser(bytes.NewBuffer(buf.Bytes()))

	// Check if request was generated by interactive element
	// Interactive element actions are always
	// sent as application/x-www-form-urlencoded
	if len(request.Header["Content-Type"]) > 0 && request.Header["Content-Type"][0] == "application/x-www-form-urlencoded" {
		request.Body = ioutil.NopCloser(bytes.NewBuffer(body))
		err = request.ParseForm()
		if err != nil {
			log.WithError(err).Error("failed to parse post body")
			common.SendInternalErrorResponse(writer, "")
			return
		}
		log.Debug("PostForm: " + fmt.Sprintf("%s", request.PostForm))
		payload := request.PostForm.Get("payload")
		log.Debug("Payload: " + payload)
		ie := &slack.InteractionCallback{}
		err := json.Unmarshal([]byte(payload), ie)
		if err != nil {
			log.WithError(err).Error("failed to parse interaction event")
			common.SendInternalErrorResponse(writer, "")
			return
		}

		data, err := json.Marshal(ie)
		if err != nil {
			log.WithError(err).Error("failed to marshal action data")
			common.SendInternalErrorResponse(writer, "")
			return
		}
		helper.ActiveEndpoints[rc.route.Webhook.Endpoint].DataCh <- data
		log.Info("request successfully processed")
		common.SendSuccessResponse(writer, "")
		return
	}

	// If there's no payload in the post body, this is likely an
	// Event API request. Parse and process if valid.
	eventsAPIEvent, err := slackevents.ParseEvent(json.RawMessage(body), slackevents.OptionVerifyToken(&slackevents.TokenComparator{VerificationToken: rc.token}))
	if err != nil {
		log.WithError(err).Error("failed to extract event")
		common.SendInternalErrorResponse(writer, "")
		return
	}

	if eventsAPIEvent.Type == slackevents.URLVerification {
		var r *slackevents.ChallengeResponse
		err := json.Unmarshal([]byte(body), &r)
		if err != nil {
			log.WithError(err).Error("failed to verify the challenge")
			common.SendInternalErrorResponse(writer, "")
			return
		}
		writer.Header().Set("Content-Type", "text")
		if _, err := writer.Write([]byte(r.Challenge)); err != nil {
			log.WithError(err).Error("failed to write the response for url verification")
			// don't return, we want to keep this running to give user chance to retry
		}
	}

	if eventsAPIEvent.Type == slackevents.CallbackEvent {
		data, err := json.Marshal(eventsAPIEvent.InnerEvent.Data)
		if err != nil {
			log.WithError(err).Error("failed to marshal event data")
			common.SendInternalErrorResponse(writer, "")
			return
		}
		helper.ActiveEndpoints[rc.route.Webhook.Endpoint].DataCh <- data
	}

	log.Info("request successfully processed")
	common.SendSuccessResponse(writer, "")
}

func (rc *RouteConfig) PostStart() error {
	return nil
}

func (rc *RouteConfig) PostStop() error {
	return nil
}

// StartEventSource starts a event source
func (ese *SlackEventSourceExecutor) StartEventSource(eventSource *gateways.EventSource, eventStream gateways.Eventing_StartEventSourceServer) error {
	defer gateways.Recover(eventSource.Name)

	log := ese.Log.WithField(common.LabelEventSource, eventSource.Name)
	log.Info("operating on event source")

	config, err := parseEventSource(eventSource.Data)
	if err != nil {
		log.WithError(err).Error("failed to parse event source")
		return err
	}

	ses := config.(*slackEventSource)

	token, err := store.GetSecrets(ese.Clientset, ese.Namespace, ses.Token.Name, ses.Token.Key)
	if err != nil {
		log.WithError(err).Error("failed to retrieve token")
		return err
	}

	signingSecret, err := store.GetSecrets(ese.Clientset, ese.Namespace, ses.SigningSecret.Name, ses.SigningSecret.Key)
	if err != nil {
		log.WithError(err).Warn("Signing secret not provided. Signature not validated.")
		signingSecret = ""
	}

	return gwcommon.ProcessRoute(&RouteConfig{
		route: &gwcommon.Route{
			Logger:      ese.Log,
			StartCh:     make(chan struct{}),
			Webhook:     ses.Hook,
			EventSource: eventSource,
		},
		token:         token,
		signingSecret: signingSecret,
		clientset:     ese.Clientset,
		namespace:     ese.Namespace,
		ses:           ses,
	}, helper, eventStream)
}
