// Code generated by protoc-gen-go. DO NOT EDIT.
// source: trigger.proto

package sensors

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// FetchResourceRequest is the request to fetch trigger resource
type FetchResourceRequest struct {
	Resource             []byte   `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FetchResourceRequest) Reset()         { *m = FetchResourceRequest{} }
func (m *FetchResourceRequest) String() string { return proto.CompactTextString(m) }
func (*FetchResourceRequest) ProtoMessage()    {}
func (*FetchResourceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c31e6d8b4368946, []int{0}
}

func (m *FetchResourceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FetchResourceRequest.Unmarshal(m, b)
}
func (m *FetchResourceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FetchResourceRequest.Marshal(b, m, deterministic)
}
func (m *FetchResourceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FetchResourceRequest.Merge(m, src)
}
func (m *FetchResourceRequest) XXX_Size() int {
	return xxx_messageInfo_FetchResourceRequest.Size(m)
}
func (m *FetchResourceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FetchResourceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FetchResourceRequest proto.InternalMessageInfo

func (m *FetchResourceRequest) GetResource() []byte {
	if m != nil {
		return m.Resource
	}
	return nil
}

// FetchResourceRequest contains the fetched resource.
type FetchResourceResponse struct {
	Resource             []byte   `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FetchResourceResponse) Reset()         { *m = FetchResourceResponse{} }
func (m *FetchResourceResponse) String() string { return proto.CompactTextString(m) }
func (*FetchResourceResponse) ProtoMessage()    {}
func (*FetchResourceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c31e6d8b4368946, []int{1}
}

func (m *FetchResourceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FetchResourceResponse.Unmarshal(m, b)
}
func (m *FetchResourceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FetchResourceResponse.Marshal(b, m, deterministic)
}
func (m *FetchResourceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FetchResourceResponse.Merge(m, src)
}
func (m *FetchResourceResponse) XXX_Size() int {
	return xxx_messageInfo_FetchResourceResponse.Size(m)
}
func (m *FetchResourceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FetchResourceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FetchResourceResponse proto.InternalMessageInfo

func (m *FetchResourceResponse) GetResource() []byte {
	if m != nil {
		return m.Resource
	}
	return nil
}

// ExecuteRequest is a request to execute a trigger resource.
type ExecuteRequest struct {
	Resource             []byte   `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExecuteRequest) Reset()         { *m = ExecuteRequest{} }
func (m *ExecuteRequest) String() string { return proto.CompactTextString(m) }
func (*ExecuteRequest) ProtoMessage()    {}
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c31e6d8b4368946, []int{2}
}

func (m *ExecuteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecuteRequest.Unmarshal(m, b)
}
func (m *ExecuteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecuteRequest.Marshal(b, m, deterministic)
}
func (m *ExecuteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecuteRequest.Merge(m, src)
}
func (m *ExecuteRequest) XXX_Size() int {
	return xxx_messageInfo_ExecuteRequest.Size(m)
}
func (m *ExecuteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecuteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ExecuteRequest proto.InternalMessageInfo

func (m *ExecuteRequest) GetResource() []byte {
	if m != nil {
		return m.Resource
	}
	return nil
}

// ExecuteResponse is the response of the trigger execution
type ExecuteResponse struct {
	Response             []byte   `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExecuteResponse) Reset()         { *m = ExecuteResponse{} }
func (m *ExecuteResponse) String() string { return proto.CompactTextString(m) }
func (*ExecuteResponse) ProtoMessage()    {}
func (*ExecuteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c31e6d8b4368946, []int{3}
}

func (m *ExecuteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecuteResponse.Unmarshal(m, b)
}
func (m *ExecuteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecuteResponse.Marshal(b, m, deterministic)
}
func (m *ExecuteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecuteResponse.Merge(m, src)
}
func (m *ExecuteResponse) XXX_Size() int {
	return xxx_messageInfo_ExecuteResponse.Size(m)
}
func (m *ExecuteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecuteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ExecuteResponse proto.InternalMessageInfo

func (m *ExecuteResponse) GetResponse() []byte {
	if m != nil {
		return m.Response
	}
	return nil
}

// ApplyPolicyRequest is the request to apply policy on the trigger execution result.
type ApplyPolicyRequest struct {
	Request              []byte   `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApplyPolicyRequest) Reset()         { *m = ApplyPolicyRequest{} }
func (m *ApplyPolicyRequest) String() string { return proto.CompactTextString(m) }
func (*ApplyPolicyRequest) ProtoMessage()    {}
func (*ApplyPolicyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c31e6d8b4368946, []int{4}
}

func (m *ApplyPolicyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApplyPolicyRequest.Unmarshal(m, b)
}
func (m *ApplyPolicyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApplyPolicyRequest.Marshal(b, m, deterministic)
}
func (m *ApplyPolicyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApplyPolicyRequest.Merge(m, src)
}
func (m *ApplyPolicyRequest) XXX_Size() int {
	return xxx_messageInfo_ApplyPolicyRequest.Size(m)
}
func (m *ApplyPolicyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ApplyPolicyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ApplyPolicyRequest proto.InternalMessageInfo

func (m *ApplyPolicyRequest) GetRequest() []byte {
	if m != nil {
		return m.Request
	}
	return nil
}

// ApplyPolicyResponse is the response of the application of the trigger policy.
type ApplyPolicyResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApplyPolicyResponse) Reset()         { *m = ApplyPolicyResponse{} }
func (m *ApplyPolicyResponse) String() string { return proto.CompactTextString(m) }
func (*ApplyPolicyResponse) ProtoMessage()    {}
func (*ApplyPolicyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c31e6d8b4368946, []int{5}
}

func (m *ApplyPolicyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApplyPolicyResponse.Unmarshal(m, b)
}
func (m *ApplyPolicyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApplyPolicyResponse.Marshal(b, m, deterministic)
}
func (m *ApplyPolicyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApplyPolicyResponse.Merge(m, src)
}
func (m *ApplyPolicyResponse) XXX_Size() int {
	return xxx_messageInfo_ApplyPolicyResponse.Size(m)
}
func (m *ApplyPolicyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ApplyPolicyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ApplyPolicyResponse proto.InternalMessageInfo

func (m *ApplyPolicyResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *ApplyPolicyResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*FetchResourceRequest)(nil), "sensors.FetchResourceRequest")
	proto.RegisterType((*FetchResourceResponse)(nil), "sensors.FetchResourceResponse")
	proto.RegisterType((*ExecuteRequest)(nil), "sensors.ExecuteRequest")
	proto.RegisterType((*ExecuteResponse)(nil), "sensors.ExecuteResponse")
	proto.RegisterType((*ApplyPolicyRequest)(nil), "sensors.ApplyPolicyRequest")
	proto.RegisterType((*ApplyPolicyResponse)(nil), "sensors.ApplyPolicyResponse")
}

func init() { proto.RegisterFile("trigger.proto", fileDescriptor_8c31e6d8b4368946) }

var fileDescriptor_8c31e6d8b4368946 = []byte{
	// 265 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0x4f, 0x4b, 0x03, 0x31,
	0x10, 0xc5, 0x59, 0x0f, 0xa6, 0x8e, 0x56, 0x21, 0x2a, 0x86, 0xf5, 0x0f, 0x65, 0x4f, 0x3d, 0xe8,
	0x1e, 0xda, 0xab, 0x17, 0x0f, 0x8a, 0x5e, 0x44, 0x82, 0x5f, 0x40, 0xc3, 0xb0, 0x16, 0x6a, 0xb3,
	0x66, 0x12, 0xb0, 0x1f, 0xd7, 0x6f, 0x22, 0x66, 0x93, 0xd0, 0xd8, 0x55, 0x7a, 0x9b, 0xb7, 0xef,
	0xbd, 0x99, 0xdd, 0x1f, 0x0b, 0x43, 0x6b, 0x66, 0x4d, 0x83, 0xa6, 0x6e, 0x8d, 0xb6, 0x9a, 0x33,
	0xc2, 0x05, 0x69, 0x43, 0xd5, 0x04, 0x8e, 0xee, 0xd0, 0xaa, 0x37, 0x89, 0xa4, 0x9d, 0x51, 0x28,
	0xf1, 0xc3, 0x21, 0x59, 0x5e, 0xc2, 0xc0, 0x84, 0x47, 0xa2, 0x18, 0x15, 0xe3, 0x3d, 0x99, 0x74,
	0x35, 0x85, 0xe3, 0x5f, 0x1d, 0x6a, 0xf5, 0x82, 0xf0, 0xdf, 0xd2, 0x25, 0xec, 0xdf, 0x7e, 0xa2,
	0x72, 0x76, 0xa3, 0x13, 0x57, 0x70, 0x90, 0xd2, 0xd9, 0x72, 0x3f, 0xaf, 0xc4, 0xbd, 0xae, 0x6a,
	0xe0, 0x37, 0x6d, 0x3b, 0x5f, 0x3e, 0xe9, 0xf9, 0x4c, 0x2d, 0xe3, 0x01, 0x01, 0xcc, 0x74, 0x63,
	0x28, 0x44, 0x59, 0x3d, 0xc0, 0x61, 0x96, 0x0f, 0x27, 0x04, 0x30, 0x72, 0x4a, 0x21, 0x91, 0x2f,
	0x0c, 0x64, 0x94, 0x3f, 0xce, 0x3b, 0x12, 0xbd, 0x34, 0x28, 0xb6, 0x46, 0xc5, 0x78, 0x47, 0x46,
	0x39, 0xf9, 0x2a, 0x80, 0x3d, 0x77, 0x6c, 0xf9, 0x23, 0x0c, 0x33, 0x30, 0xfc, 0xbc, 0x0e, 0x9c,
	0xeb, 0x3e, 0xc8, 0xe5, 0xc5, 0x5f, 0x76, 0x78, 0x9f, 0x6b, 0x60, 0x81, 0x02, 0x3f, 0x49, 0xd1,
	0x9c, 0x62, 0x29, 0xd6, 0x8d, 0xd0, 0xbe, 0x87, 0xdd, 0x95, 0x8f, 0xe4, 0xa7, 0x29, 0xb8, 0x8e,
	0xaa, 0x3c, 0xeb, 0x37, 0xbb, 0x4d, 0xaf, 0xdb, 0xfe, 0xa7, 0x99, 0x7e, 0x07, 0x00, 0x00, 0xff,
	0xff, 0x45, 0x17, 0xfa, 0x62, 0x45, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TriggerClient is the client API for Trigger service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TriggerClient interface {
	// FetchResource fetches the resource to be triggered.
	FetchResource(ctx context.Context, in *FetchResourceRequest, opts ...grpc.CallOption) (*FetchResourceResponse, error)
	// Execute executes the requested trigger resource.
	Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (*ExecuteResponse, error)
	// ApplyPolicy applies policies on the trigger execution result.
	ApplyPolicy(ctx context.Context, in *ApplyPolicyRequest, opts ...grpc.CallOption) (*ApplyPolicyResponse, error)
}

type triggerClient struct {
	cc *grpc.ClientConn
}

func NewTriggerClient(cc *grpc.ClientConn) TriggerClient {
	return &triggerClient{cc}
}

func (c *triggerClient) FetchResource(ctx context.Context, in *FetchResourceRequest, opts ...grpc.CallOption) (*FetchResourceResponse, error) {
	out := new(FetchResourceResponse)
	err := c.cc.Invoke(ctx, "/sensors.Trigger/FetchResource", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *triggerClient) Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (*ExecuteResponse, error) {
	out := new(ExecuteResponse)
	err := c.cc.Invoke(ctx, "/sensors.Trigger/Execute", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *triggerClient) ApplyPolicy(ctx context.Context, in *ApplyPolicyRequest, opts ...grpc.CallOption) (*ApplyPolicyResponse, error) {
	out := new(ApplyPolicyResponse)
	err := c.cc.Invoke(ctx, "/sensors.Trigger/ApplyPolicy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TriggerServer is the server API for Trigger service.
type TriggerServer interface {
	// FetchResource fetches the resource to be triggered.
	FetchResource(context.Context, *FetchResourceRequest) (*FetchResourceResponse, error)
	// Execute executes the requested trigger resource.
	Execute(context.Context, *ExecuteRequest) (*ExecuteResponse, error)
	// ApplyPolicy applies policies on the trigger execution result.
	ApplyPolicy(context.Context, *ApplyPolicyRequest) (*ApplyPolicyResponse, error)
}

// UnimplementedTriggerServer can be embedded to have forward compatible implementations.
type UnimplementedTriggerServer struct {
}

func (*UnimplementedTriggerServer) FetchResource(ctx context.Context, req *FetchResourceRequest) (*FetchResourceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchResource not implemented")
}
func (*UnimplementedTriggerServer) Execute(ctx context.Context, req *ExecuteRequest) (*ExecuteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Execute not implemented")
}
func (*UnimplementedTriggerServer) ApplyPolicy(ctx context.Context, req *ApplyPolicyRequest) (*ApplyPolicyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApplyPolicy not implemented")
}

func RegisterTriggerServer(s *grpc.Server, srv TriggerServer) {
	s.RegisterService(&_Trigger_serviceDesc, srv)
}

func _Trigger_FetchResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchResourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TriggerServer).FetchResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sensors.Trigger/FetchResource",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TriggerServer).FetchResource(ctx, req.(*FetchResourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Trigger_Execute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TriggerServer).Execute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sensors.Trigger/Execute",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TriggerServer).Execute(ctx, req.(*ExecuteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Trigger_ApplyPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyPolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TriggerServer).ApplyPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sensors.Trigger/ApplyPolicy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TriggerServer).ApplyPolicy(ctx, req.(*ApplyPolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Trigger_serviceDesc = grpc.ServiceDesc{
	ServiceName: "sensors.Trigger",
	HandlerType: (*TriggerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FetchResource",
			Handler:    _Trigger_FetchResource_Handler,
		},
		{
			MethodName: "Execute",
			Handler:    _Trigger_Execute_Handler,
		},
		{
			MethodName: "ApplyPolicy",
			Handler:    _Trigger_ApplyPolicy_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "trigger.proto",
}
