/*
Copyright 2021 The Argoproj Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/argoproj/argo-events/pkg/apis/events/v1alpha1"
	eventsv1alpha1 "github.com/argoproj/argo-events/pkg/client/clientset/versioned/typed/events/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeEventBus implements EventBusInterface
type fakeEventBus struct {
	*gentype.FakeClientWithList[*v1alpha1.EventBus, *v1alpha1.EventBusList]
	Fake *FakeArgoprojV1alpha1
}

func newFakeEventBus(fake *FakeArgoprojV1alpha1, namespace string) eventsv1alpha1.EventBusInterface {
	return &fakeEventBus{
		gentype.NewFakeClientWithList[*v1alpha1.EventBus, *v1alpha1.EventBusList](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("eventbus"),
			v1alpha1.SchemeGroupVersion.WithKind("EventBus"),
			func() *v1alpha1.EventBus { return &v1alpha1.EventBus{} },
			func() *v1alpha1.EventBusList { return &v1alpha1.EventBusList{} },
			func(dst, src *v1alpha1.EventBusList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.EventBusList) []*v1alpha1.EventBus { return gentype.ToPointerSlice(list.Items) },
			func(list *v1alpha1.EventBusList, items []*v1alpha1.EventBus) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
